# Generated by Django 5.0.14 on 2026-09-28 06:51

import apps.common.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('RESTRICTED', 'Restricted'), ('SUSPENDED', 'Suspended'), ('DEACTIVATED', 'Deactivated')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='known_ips',
            field=models.JSONField(blank=True, default=list, help_text='Capped list of previously seen IPs — new IP = risk signal'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='suspended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspensions_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_until',
            field=models.DateTimeField(blank=True, help_text='NULL = indefinite', null=True),
        ),
        migrations.AlterField(
            model_name='hostprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.validators.SecureUploadPath('hosts')),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.validators.SecureUploadPath('avatars')),
        ),
    ]
