# Generated by Django 5.0.14 on 2026-09-28 06:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('LOGIN_FAILED', 'Login Failed'), ('LOGIN_SUCCESS', 'Login Success'), ('SUSPICIOUS_LOGIN', 'Suspicious Login'), ('PASSWORD_CHANGED', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset'), ('ACCOUNT_LOCKED', 'Account Locked'), ('ACCOUNT_SUSPENDED', 'Account Suspended'), ('TOKEN_REVOKED', 'Token Revoked'), ('PERMISSION_DENIED', 'Permission Denied'), ('RATE_LIMIT_TRIGGERED', 'Rate Limit Triggered'), ('WEBHOOK_SIGNATURE_FAILED', 'Webhook Signature Failed'), ('PAYMENT_ANOMALY', 'Payment Anomaly'), ('ADMIN_ACTION', 'Admin Action'), ('FILE_UPLOAD_REJECTED', 'File Upload Rejected'), ('OTP_FAILED', 'OTP Failed')], db_index=True, max_length=40)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('resource_type', models.CharField(blank=True, max_length=60)),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events_resolved', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_ref', models.CharField(db_index=True, max_length=20, unique=True)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, max_length=10)),
                ('incident_type', models.CharField(db_index=True, max_length=60)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('affected_service', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('DETECTED', 'Detected'), ('INVESTIGATING', 'Investigating'), ('CONTAINED', 'Contained'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='DETECTED', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_assigned', to=settings.AUTH_USER_MODEL)),
                ('events', models.ManyToManyField(blank=True, related_name='incidents', to='security.securityevent')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', '-created_at'], name='security_se_event_t_f256e1_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['severity', '-created_at'], name='security_se_severit_a311e5_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['user', '-created_at'], name='security_se_user_id_8d1054_idx'),
        ),
    ]
