# Generated by Django 5.0.14 on 2026-09-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_FAILED', 'Login Failed'), ('LOGIN_SUCCESS', 'Login Success'), ('SUSPICIOUS_LOGIN', 'Suspicious Login'), ('PASSWORD_CHANGED', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset'), ('ACCOUNT_LOCKED', 'Account Locked'), ('ACCOUNT_SUSPENDED', 'Account Suspended'), ('ACCOUNT_RESTORED', 'Account Restored'), ('ACCOUNT_RESTRICTED', 'Account Restricted'), ('TOKEN_REVOKED', 'Token Revoked'), ('EMAIL_VERIFIED', 'Email Verified'), ('PHONE_VERIFIED', 'Phone Verified'), ('PERMISSION_CHANGE', 'Permission Change'), ('PERMISSION_DENIED', 'Permission Denied'), ('RATE_LIMIT_TRIGGERED', 'Rate Limit Triggered'), ('WEBHOOK_SIGNATURE_FAILED', 'Webhook Signature Failed'), ('PAYMENT_ANOMALY', 'Payment Anomaly'), ('ADMIN_ACTION', 'Admin Action'), ('FILE_UPLOAD_REJECTED', 'File Upload Rejected'), ('OTP_FAILED', 'OTP Failed')], db_index=True, max_length=40),
        ),
    ]
