# Generated by Django 5.0.14 on 2026-09-28 06:51

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_approved_at_property_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydocument',
            name='file',
            field=models.FileField(upload_to=apps.common.validators.SecureUploadPath('property-documents')),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to=apps.common.validators.SecureUploadPath('properties/images'), validators=[apps.common.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='propertyvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.validators.SecureUploadPath('properties/videos/thumbs'), validators=[apps.common.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='propertyvideo',
            name='video',
            field=models.FileField(upload_to=apps.common.validators.SecureUploadPath('properties/videos')),
        ),
    ]
