# Generated by Django 5.0.14 on 2026-09-28 07:59

import secrets

from django.db import migrations, models
from django.utils.text import slugify


def backfill_slugs(apps, schema_editor):
    Property = apps.get_model("properties", "Property")
    seen = set()
    for prop in Property.objects.all().iterator():
        base = slugify(prop.title)[:190] or "stay"
        slug = base
        while slug in seen or Property.objects.filter(slug=slug).exists():
            slug = f"{base}-{secrets.token_hex(3)}"
        prop.slug = slug
        prop.save(update_fields=["slug"])
        seen.add(slug)


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_propertydocument_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, help_text='Public URL slug — stable, generated once from the title.', max_length=220, null=True, unique=True),
        ),
        migrations.RunPython(backfill_slugs, migrations.RunPython.noop),
    ]
