# Generated by Django 5.0.14 on 2026-09-28 21:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyUnit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='How many identical units of this type exist.')),
                ('max_guests', models.PositiveIntegerField(default=1)),
                ('beds', models.PositiveIntegerField(default=1)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.DecimalField(decimal_places=1, default=1, max_digits=3)),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, help_text='Nightly price override; empty falls back to property base price.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['property', 'is_active'], name='properties__propert_ba0185_idx')],
            },
        ),
    ]
