# Generated by Django 5.0.14 on 2026-09-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostwallet',
            name='pending_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Funds held by open payout requests', max_digits=14),
        ),
        migrations.AddField(
            model_name='payout',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
