# Generated by Django 5.0.14 on 2026-09-28 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('availability', '0001_initial'),
        ('bookings', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilitydate',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_dates', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='availabilitydate',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_dates', to='properties.property'),
        ),
        migrations.AddIndex(
            model_name='availabilitydate',
            index=models.Index(fields=['property', 'date', 'status'], name='availabilit_propert_d3fb49_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilitydate',
            index=models.Index(fields=['property', 'status'], name='availabilit_propert_24f808_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='availabilitydate',
            unique_together={('property', 'date')},
        ),
    ]
