# Generated by Django 5.0.14 on 2026-09-28 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_initial'),
        ('bookings', '0005_booking_unit_booking_unit_name'),
        ('properties', '0005_propertyunit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availabilitydate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='availabilitydate',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='When set, this row applies to one unit inside the property.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_dates', to='properties.propertyunit'),
        ),
        migrations.AddIndex(
            model_name='availabilitydate',
            index=models.Index(fields=['unit', 'date'], name='availabilit_unit_id_2c65e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='availabilitydate',
            constraint=models.UniqueConstraint(condition=models.Q(('unit__isnull', False)), fields=('property', 'unit', 'date'), name='uniq_avail_prop_unit_date'),
        ),
        migrations.AddConstraint(
            model_name='availabilitydate',
            constraint=models.UniqueConstraint(condition=models.Q(('unit__isnull', True)), fields=('property', 'date'), name='uniq_avail_prop_date_no_unit'),
        ),
    ]
