# Generated by Django 5.0.14 on 2026-09-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0003_alter_availabilitydate_unique_together_and_more'),
        ('bookings', '0006_alter_booking_status'),
        ('properties', '0005_propertyunit'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='availabilitydate',
            name='uniq_avail_prop_unit_date',
        ),
        migrations.AddConstraint(
            model_name='availabilitydate',
            constraint=models.UniqueConstraint(condition=models.Q(('booking__isnull', False), ('unit__isnull', False)), fields=('unit', 'date', 'booking'), name='uniq_avail_unit_date_booking'),
        ),
        migrations.AddConstraint(
            model_name='availabilitydate',
            constraint=models.UniqueConstraint(condition=models.Q(('booking__isnull', True), ('unit__isnull', False)), fields=('unit', 'date'), name='uniq_avail_unit_date_no_booking'),
        ),
    ]
