# Generated by Django 5.0.14 on 2026-09-28 05:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('locations', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Percent'), ('FIXED', 'Fixed Amount')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(blank=True, help_text='Required for FIXED discounts', max_length=3)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('per_user_limit', models.PositiveIntegerField(default=1)),
                ('min_booking_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Cap for PERCENT discounts', max_digits=12, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('country', models.ForeignKey(blank=True, help_text='NULL = all countries', null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.country')),
                ('properties', models.ManyToManyField(blank=True, help_text='Empty = applies to all properties', related_name='promotions', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_usage', to='bookings.booking')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='promotions.promotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_usages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['code', 'is_active'], name='promotions__code_841910_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionusage',
            index=models.Index(fields=['promotion', 'user'], name='promotions__promoti_ac6da2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='promotionusage',
            unique_together={('promotion', 'booking')},
        ),
    ]
