# Generated by Django 5.0.14 on 2026-09-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='raw_body',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='raw_signature',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
