# Generated by Django 5.0.14 on 2026-09-28 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='properties.property'),
        ),
        migrations.AddField(
            model_name='bookingcancellation',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingcancellation',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellations_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingguest',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingprice',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingstatushistory',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.cancellationpolicy'),
        ),
        migrations.AddField(
            model_name='cancellationrule',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='bookings.cancellationpolicy'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['guest', 'status', '-created_at'], name='bookings_bo_guest_i_85e0b9_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['property', 'check_in', 'check_out'], name='bookings_bo_propert_b6e6e3_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['property', 'status'], name='bookings_bo_propert_92bdff_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'expires_at'], name='bookings_bo_status_86acff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cancellationrule',
            unique_together={('policy', 'hours_before_check_in')},
        ),
    ]
