# Generated by Django 5.0.14 on 2026-09-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Client-supplied Idempotency-Key; retries return the same booking', max_length=64, null=True, unique=True),
        ),
    ]
