# Generated by Django 5.0.14 on 2026-09-28 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_adults_booking_cancellation_policy_name_and_more'),
        ('properties', '0005_propertyunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Optional unit/room booked inside a multi-unit property.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='properties.propertyunit'),
        ),
        migrations.AddField(
            model_name='booking',
            name='unit_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
