# Generated by Django 5.0.14 on 2026-09-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_unit_booking_unit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('CHECKED_IN', 'Checked In'), ('COMPLETED', 'Completed'), ('REFUNDED', 'Refunded'), ('DISPUTED', 'Disputed'), ('EXPIRED', 'Expired'), ('NO_SHOW', 'No Show')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
