# Generated by Django 5.0.14 on 2026-09-28 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('locations', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionrule',
            name='property_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.propertytype'),
        ),
        migrations.AddField(
            model_name='taxrule',
            name='country',
            field=models.ForeignKey(blank=True, help_text='NULL = applies globally', null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.country'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-created_at'], name='admin_panel_action_a0d9ca_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor', '-created_at'], name='admin_panel_actor_i_d51a91_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_type', 'target_id'], name='admin_panel_target__d12bc8_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionrule',
            index=models.Index(fields=['scope', 'is_active'], name='admin_panel_scope_62e340_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrule',
            index=models.Index(fields=['country', 'is_active'], name='admin_panel_country_e3fa4c_idx'),
        ),
    ]
