# Generated by Django 5.0.14 on 2026-09-28 06:51

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdocument',
            name='file',
            field=models.FileField(upload_to=apps.common.validators.SecureUploadPath('kyc')),
        ),
    ]
